# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b051cd5123e4dc2dfee672a69256de2d32247910fa1b088288d15a6728857752ed5e1926e249ed9d7c9fea0d906de1335e9c043326f8d80f861263438a38840c

test:
  secret_key_base: a5a01c298a672284f6febcaf4b1c2f70cf633f9fb2a967d773c99642864abceb04b81156a9dcd809094335c0d6eca53120a13fd05f129833147886c2edd14bc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
